spring:
  liquibase:
    change-log: classpath:/liquibase/changelog.yaml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
    open-in-view: false
#    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost/reactive_spring
    username: admin

management:
  metrics:
    export:
      prometheus:
        enabled:
          true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 24895