spring:
  liquibase:
    change-log: classpath:/liquibase/changelog.yaml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
    open-in-view: false
#    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost/reactive_spring
    username: admin

server:
  port: 24895