spring:
  r2dbc:
    url: r2dbc:postgresql://localhost/reactive_spring
    username: admin

server:
  port: 24995


#logging:
#  level:
#    io.r2dbc.postgresql.QUERY: DEBUG # for queries
#    io.r2dbc.postgresql.PARAM: DEBUG # for parameters