spring:
  r2dbc:
    url: r2dbc:postgresql://localhost/reactive_spring
    username: admin

server:
  port: 24995

management:
  metrics:
    export:
      prometheus:
        enabled:
          true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

#logging:
#  level:
#    io.r2dbc.postgresql.QUERY: DEBUG # for queries
#    io.r2dbc.postgresql.PARAM: DEBUG # for parameters